---
title: "People"
description: Participants and Organization
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Core Faculty

[Lisa Beinborn](https://beinborn.eu), University of Amsterdam

[Karsten Donnay](https://www.karstendonnay.net), University of Zurich

[David Garcia](https://dgarcia.eu), University of Konstanz

[Iryna Gurevych](https://www.informatik.tu-darmstadt.de/ukp/ukp_home/head_ukp/index.en.jsp), TU Darmstadt

[Jutta Mata](https://www.sowi.uni-mannheim.de/mata/), University of Mannheim

[Markus Strohmaier](http://markusstrohmaier.info), University of Mannheim

[Heiner Stuckenschmidt](https://www.uni-mannheim.de/dws/people/professors/prof-dr-heiner-stuckenschmidt/), University of Mannheim

[Claudia Wagner](http://claudiawagner.info), RWTH Aachen University

[Robert West](https://people.epfl.ch/robert.west), Swiss Federal Institute of Technology, Lausanne

[Dirk Wulff](https://beinborn.eu), Max Planck Institute for Human Development

[Rui Mata](https://psychologie.unibas.ch/de/fakultaet/abteilungen/cognitive-and-decision-sciences-305/), University of Basel

### Additional Participants

Additional participants (doctoral candidates, postdocs) will be invited to participate and contribute actively to the discussion and all workshop events. 

<!-- Potential additional participants as a function of core faculty recommendations: -->

<!-- [Hendrik Schuff](https://hendrikschuff.de), University of Stuttgart -->

<!-- [Marlene Lutz](https://www.bwl.uni-mannheim.de/en/information-systems/chairs/prof-dr-strohmaier/team/academic-staff/marlene-lutz/), University of Mannheim -->

<!-- [Max Pellert](https://mpellert.at/), University of Mannheim -->

<!-- [Zakir Hussain](https://psychologie.unibas.ch/de/personen/zakir-hussain/about-me/), University of Basel -->

<!-- [Samuel Aeschbach](https://samuelaeschbach.com), Max Planck Institute for Human Development -->

<!-- [Shahar Hechtlinger](https://www.mpib-berlin.mpg.de/person/102108), Max Planck Institute for Human Development -->

<!-- [Ezequiel López López](https://www.mpib-berlin.mpg.de/person/ezequiel-lopez-lopez/171978), Max Planck Institute for Human Development -->

<!-- [Christine Emmer](https://www.sowi.uni-mannheim.de/mata/team/akademische-mitarbeiterinnen-und-mitarbeiter/christine-emmer/), University of Mannheim -->

### Organization

The LLMs for Behavioral Science workshop has been organized by Dirk Wulff, Markus Strohmaier, and Rui Mata. Administrative support provided by Laura Wiles, Center for Cognitive and Decision Sciences, University of Basel. 